--
CREATE TABLE car
(
    id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand VARCHAR,
    model VARCHAR,
    cost  INTEGER
);
--
CREATE TABLE human
(
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR,
    age                 INTEGER,
    has_driving_licence BOOLEAN,
    car_id              INTEGER REFERENCES car (id) NOT NULL
);