-- liquibase formatted sql

-- changeset alrepin:1
CREATE TABLE IF NOT EXISTS public.notification_task
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id   BIGINT    NOT NULL,
    text      TEXT      NOT NULL,
    date_time TIMESTAMP NOT NULL
);
